import { StyleSheet } from 'react-native';
import type { ColorTokens } from '@/constants/colors';

export function makeEditMemberStyles(colors: ColorTokens) {
  return StyleSheet.create({
    backdrop: { flex: 1 },
    sheet: {
      backgroundColor: colors.bgCard,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      paddingBottom: 40,
    },
    handle: {
      width: 40,
      height: 4,
      backgroundColor: colors.border,
      borderRadius: 2,
      alignSelf: 'center',
      marginBottom: 20,
    },
    title: {
      fontFamily: 'Georgia',
      fontSize: 22,
      fontWeight: '600',
      color: colors.textPrimary,
      marginBottom: 20,
    },
    input: {
      backgroundColor: colors.bgDeep,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontFamily: 'Georgia',
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 20,
    },
    sectionLabel: {
      fontFamily: 'monospace',
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 1.2,
      color: colors.textSecondary,
      marginBottom: 12,
    },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 24 },
    chip: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 99,
      paddingVertical: 8,
      paddingHorizontal: 14,
    },
    chipActive: {
      borderColor: colors.accentBlue,
      backgroundColor: 'rgba(59,130,246,0.12)',
    },
    chipText: { fontFamily: 'Georgia', fontSize: 14, color: colors.textSecondary },
    chipTextActive: { color: colors.accentBlue },
    shareRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bgDeep,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginBottom: 24,
      gap: 12,
    },
    shareTitle: {
      fontFamily: 'Georgia',
      fontSize: 15,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    shareSub: {
      fontFamily: 'Georgia',
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    saveBtn: {
      backgroundColor: colors.accentBlue,
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: 'center',
    },
    saveBtnDisabled: { opacity: 0.4 },
    saveText: {
      fontFamily: 'monospace',
      fontSize: 13,
      fontWeight: '600',
      letterSpacing: 1.2,
      color: '#ffffff',
    },
    removeBtn: {
      borderWidth: 1,
      borderColor: colors.warningRed,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 12,
    },
    removeText: {
      fontFamily: 'monospace',
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 1.2,
      color: colors.warningRed,
    },
  });
}
